SELECT * FROM CUSTOMER LIMIT 10;

--Q1. What is the total revenue generated by sale vs. female customers?
select gender, SUM(purchase amount) as revenue
from customer
group by gender;

--Q.2 Identify customers who used a discount and spent more than average
SELECT "Customer ID", "Purchase Amount (USD)"
FROM customer
WHERE "Discount Applied" = 'Yes' AND "Purchase Amount (USD)" > (SELECT AVG("Purchase Amount (USD)") FROM customer);

--Q.3 which are the top 5 products with highest review rating?
SELECT "Item Purchased", AVG("Review Rating") as "Average Product Rating"
FROM customer
GROUP BY "Item Purchased"
ORDER BY AVG("Review Rating") DESC
LIMIT 5;

--Q.4 Compare the average purchase Amounts between standard and express shipping?
SELECT "Shipping Type",
AVG("Purchase Amount (USD)")
FROM customer
WHERE "Shipping Type" in ('Express', 'Standard')
GROUP BY "Shipping Type";

--Q.5 Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers
SELECT "Subscription Status",
COUNT("Customer ID") as "total_customers",
ROUND(AVG("Purchase Amount (USD)"),2) as "avg_spend",
ROUND(SUM("Purchase Amount (USD)"),2) as "total_revenue"
FROM customer
GROUP BY "Subscription Status"
ORDER BY "total_revenue","avg_spend" DESC;

--Q.6 Which 5 products have the highest percentage of purchases with discount applied?
SELECT "Item Purchased",
ROUND(100*SUM(CASE WHEN "Discount Applied" ='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as "Discount Rate"
FROM customer
GROUP BY "Item Purchased"
ORDER BY "Discount Rate" DESC
LIMIT 5;

--Q.7 Segment customers in new ,Returning and loal based on their total
-- number of previous purchases, and show the count of each segment.
WITH Customer_type as(
SELECT "Customer ID","Previous Purchases",
CASE
    WHEN "Previous Purchases" = 1 THEN 'New'
	WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS Customer_segment
FROM customer
)

SELECT Customer_segment,COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY Customer_segment

--Q.8 What are the top 3 most purchased products within each category?
WITH item_counts AS(
SELECT "Category",
"Item Purchased",
COUNT("Customer ID")as total_orders,
ROW_NUMBER() OVER(PARTITION BY "Category" ORDER BY COUNT("Customer ID")DESC) AS "item_rank"
FROM customer
GROUP BY "Category", "Item Purchased"
)

SELECT "item_rank", "Category", "Item Purchased", "total_orders"
from item_counts
where "item_rank" <= 3;

--Q.9 Are customers who are repeat buyers (more than 5 previous purchases) alsi likely to subscribe?
SELECT "Subscription Status",
COUNT ("Customer ID") AS "repeat_buyers"
from customer
where "Previous Purchases" > 5
group by "Subscription Status"

--Q.10 What is the revenue contribuition of each age group?

SELECT "Age",
SUM("Purchase Amount (USD)") AS total_revenue
from customer
GROUP BY "Age"
ORDER BY "total_revenue" DESC;
